# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 遂州创信
subtitle: 蓝江老涌的博客
description: 学习总结 思考感悟 知识管理 # 网站描述
author: 遂州创信
email: 87389166@qq.com
language: zh-Hans

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://szcx.coding.me  
##url: http://szcx.gitcafe.com  #这个绑定域名:http://snljzz.tk
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
permalink_defaults:

# Directory
source_dir: source
public_dir: public

# Writing 文章布局、写作格式的定义，不修改
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 1
tag: 1

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: localhost
logger: false
logger_format: dev


#启用插件

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-D
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 6 #每页6篇文章
pagination_dir: page

# Disqus #社会化评论disqus，我使用多说，在主题中配置
disqus_shortname:

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: light
#主题预览执行：hexo clean && hexo s
#theme: yilia yelee light

# 自动生成sitemap
#sitemap:
#path: sitemap.xml
#baidusitemap:
#path: baidusitemap.xml

exclude_generator:

#  Deployment 站点部署到github要配置，上一节中已经讲过
## Docs: http://zespia.tw/hexo/docs/deploy.html
#deploy:
  #type: github
  #repository: git@gitcafe.com:szcx/szcx.git
  #branch: gitcafe-pages
 #部署文件用代码 
deploy: 
  type: git
  repo: 
   github: git@github.com:ljzz/ljzz.github.io.git,master
#   coding: git@git.coding.net:szcx/szcx.git,coding-pages
#   oschina: git@git.oschina.net:szcx/szcx.git,master
#   github: https://github.com/ljzz/ljzz.github.io.git,master
#   coding: https://git.coding.net/szcx/szcx.git,coding-pages
#   oschina: https://git.oschina.net/szcx/szcx.git,master
#备份全部点文件  
#backup:
#    type: git
#    message: update c 
#    repository:   
#      github: git@github.com:ljzz/ljzz.github.io.git,blog
#      coding: https://git.coding.net/szcx/szcx.git,blog
#      oschina: https://git.oschina.net/szcx/szcx.git,blog